import { useEffect, useState, type FormEvent } from 'react';
import type { CoreClient } from '../../domain/ipc';
import type { Concept, Effect, EffectType, Player, SessionEffect, SessionEffectRole } from '../../domain/world';
import './SessionEffectsPanel.css';

const roles: SessionEffectRole[] = ['relevant','applied','removed','observed'];
const roleLabel = (role:SessionEffectRole) => role.replaceAll('_',' ');
type Props={client:CoreClient;player:Player;sessionId:string;effects:Effect[];concepts:Concept[];onOpenEffect:(id:string)=>void;onRefresh:()=>Promise<void>};
export function SessionEffectsPanel({client,player,sessionId,effects,concepts,onOpenEffect,onRefresh}:Props){
  const [links,setLinks]=useState<SessionEffect[]>([]);const [types,setTypes]=useState<EffectType[]>([]);
  const [effectId,setEffectId]=useState('');const [role,setRole]=useState<SessionEffectRole>('relevant');
  const [typeCode,setTypeCode]=useState('buff');const [name,setName]=useState('');const [description,setDescription]=useState('');const [conceptId,setConceptId]=useState('');const [intensity,setIntensity]=useState('1');
  const [expiring,setExpiring]=useState(false);const [expiresAt,setExpiresAt]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(){const rows=await client.listSessionEffects(player.id,sessionId);setLinks(rows);}
  useEffect(()=>{let live=true;void Promise.all([client.listSessionEffects(player.id,sessionId),client.listEffectTypes()]).then(([rows,available])=>{if(!live)return;setLinks(rows);setTypes(available);if(available[0])setTypeCode(available[0].code)}).catch(reason=>{if(live)setError(reason instanceof Error?reason.message:'Session Effect context could not be loaded.')});return()=>{live=false}},[client,player.id,sessionId]);
  async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await fn();await load();await onRefresh();setMessage(success)}catch(reason){setError(reason instanceof Error?reason.message:'Session Effect action failed.')}finally{setBusy(false)}}
  const activeLinks=links.filter(link=>link.removedAt===null);
  const linkedIds=new Set(activeLinks.map(link=>link.effectId));
  const availableEffects=effects.filter(effect=>!linkedIds.has(effect.id));
  function create(event:FormEvent){event.preventDefault();if(!name.trim()||!typeCode)return;void action(()=>client.createEffect(player.id,{typeCode,name:name.trim(),description:description.trim()||undefined,targetConceptId:conceptId||null,intensity:Number(intensity),expiresAt:expiring&&expiresAt?new Date(expiresAt).toISOString():null},sessionId).then(()=>{setName('');setDescription('');setConceptId('');setIntensity('1');setExpiring(false);setExpiresAt('')}),'Effect created and explicitly recorded as applied during this Session.')}
  return <section className="surface-card session-effects"><div className="surface-card__heading"><div><p className="eyebrow">EXPLICIT CONTEXT · NOT INFERRED</p><h3>Effects in this Session</h3></div><span>{activeLinks.length} links</span></div><p className="muted">Only relationships you explicitly recorded appear here. Removing a link never deactivates or deletes its Effect.</p>
    {message&&<p className="effect-feedback" role="status">{message}</p>}{error&&<p className="effect-feedback effect-feedback--error" role="alert">{error}</p>}
    {activeLinks.length===0?<p className="muted">No Effects have been explicitly linked to this Session.</p>:<div className="session-effects__list">{activeLinks.map(link=>{const effect=effects.find(item=>item.id===link.effectId);return <div className="session-effects__row" key={link.id}><span className="type-pill">{roleLabel(link.role)}</span>{effect?<button className="text-link" onClick={()=>onOpenEffect(effect.id)}>{effect.name}</button>:<span>Unavailable Effect record</span>}<small>{effect?`${effect.typeCode} · ${effect.expiresAt?'expiry recorded':'no expiry recorded'}`:'Relationship preserved'}</small><button className="button button--small button--quiet" disabled={busy} onClick={()=>void action(()=>client.unlinkEffectFromSession(player.id,sessionId,link.id),'Session link removed; both records remain unchanged.')}>Remove link</button></div>})}</div>}
    <div className="session-effects__controls"><form onSubmit={event=>{event.preventDefault();if(!effectId)return;void action(()=>client.linkEffectToSession(player.id,sessionId,effectId,role),'Existing Effect linked explicitly to this Session.')}}><strong>Add existing Effect</strong><div className="session-effects__inline"><label>Effect<select value={effectId} onChange={event=>setEffectId(event.target.value)}><option value="">Choose an Effect</option>{availableEffects.map(effect=><option key={effect.id} value={effect.id}>{effect.name} · {effect.typeCode}</option>)}</select></label><label>Role<select value={role} onChange={event=>setRole(event.target.value as SessionEffectRole)}>{roles.map(value=><option key={value} value={value}>{roleLabel(value)}</option>)}</select></label><button className="button button--small" disabled={busy||!effectId}>Add to Session</button></div></form>
      <form onSubmit={create}><strong>Create an Effect in this Session</strong><p className="muted">This explicit action creates an Effect and an “applied” Session relationship atomically.</p><div className="session-effects__inline"><label>Type<select value={typeCode} onChange={event=>setTypeCode(event.target.value)}>{types.map(type=><option key={type.code} value={type.code}>{type.label}</option>)}</select></label><label>Name<input required value={name} onChange={event=>setName(event.target.value)} placeholder="Effect name"/></label><label>Description<input value={description} onChange={event=>setDescription(event.target.value)} placeholder="Optional"/></label><label>Target<select value={conceptId} onChange={event=>setConceptId(event.target.value)}><option value="">Player</option>{concepts.map(concept=><option key={concept.id} value={concept.id}>Concept · {concept.name}</option>)}</select></label><label>Intensity<input type="number" step="1" value={intensity} onChange={event=>setIntensity(event.target.value)}/></label></div><div className="session-effects__inline session-effects__expiry"><label className="session-effects__check"><input type="checkbox" checked={expiring} onChange={event=>setExpiring(event.target.checked)}/> Record an expiry</label>{expiring&&<label>Expires at<input required type="datetime-local" value={expiresAt} onChange={event=>setExpiresAt(event.target.value)}/></label>}<button className="button button--small button--primary" disabled={busy||!name.trim()||types.length===0}>Create in Session</button></div></form></div>
  </section>;
}
