import { useEffect, useState } from 'react';
import type { CoreClient } from '../../domain/ipc';
import type { Tag, TagTargetKind, TaggedRecord } from '../../domain/world';

type Props={client:CoreClient;playerId:string;targetKind:TagTargetKind;targetId:string;onOpenTag:(id:string)=>void};
export function TagAssignments({client,playerId,targetKind,targetId,onOpenTag}:Props){
 const [choices,setChoices]=useState<Tag[]>([]);const [assigned,setAssigned]=useState<TaggedRecord[]>([]);const [tagId,setTagId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function refresh(){if(typeof client.listTags!=='function'||typeof client.listTagsForTarget!=='function')return;const [tags,rows]=await Promise.all([client.listTags(playerId),client.listTagsForTarget(playerId,targetKind,targetId)]);setChoices(tags);setAssigned(rows);setTagId(current=>tags.some(tag=>tag.id===current&&!rows.some(row=>row.tag.id===current))?current:tags.find(tag=>!rows.some(row=>row.tag.id===tag.id))?.id??'')}
 useEffect(()=>{let live=true;if(typeof client.listTags!=='function'||typeof client.listTagsForTarget!=='function'){setChoices([]);setAssigned([]);return()=>{live=false}}void Promise.all([client.listTags(playerId),client.listTagsForTarget(playerId,targetKind,targetId)]).then(([tags,rows])=>{if(!live)return;setChoices(tags);setAssigned(rows);setTagId(tags.find(tag=>!rows.some(row=>row.tag.id===tag.id))?.id??'')}).catch(reason=>{if(live)setError(reason instanceof Error?reason.message:'Tags could not be loaded.')});return()=>{live=false}},[client,playerId,targetKind,targetId]);
 const mutate=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await refresh()}catch(reason){setError(reason instanceof Error?reason.message:'The Tag assignment could not be changed.')}finally{setBusy(false)}};
 return <section className="surface-card tag-assignments" aria-label="Tags on this record"><div className="surface-card__heading"><div><p className="eyebrow">PLAYER-ASSIGNED ORGANIZATION</p><h3>Tags</h3></div><button type="button" className="text-link" onClick={()=>onOpenTag('')}>Manage Tags</button></div><p className="muted">Current Tags are independent of this record’s Concept, status, lifecycle, and visibility.</p>{assigned.length===0?<p className="muted">No Tags assigned.</p>:<div className="tag-assignment-list">{assigned.map(row=><div className="tag-assignment-row" key={row.relationship.id}><button type="button" className="tag-name-link" onClick={()=>onOpenTag(row.tag.id)}>{row.tag.name}</button><span className={`lifecycle lifecycle--${row.tag.lifecycle}`}>{row.tag.lifecycle}</span><button type="button" className="button button--small button--quiet" aria-label={`Remove Tag ${row.tag.name}`} disabled={busy} onClick={()=>void mutate(()=>client.detachTag(playerId,row.relationship.id))}>Remove</button></div>)}</div>}<form className="tag-assignment-form" onSubmit={event=>{event.preventDefault();if(!tagId)return;void mutate(()=>client.attachTag(playerId,tagId,targetKind,targetId))}}><label>Add an active Tag<select value={tagId} onChange={event=>setTagId(event.target.value)}><option value="">{choices.length?'Choose a Tag':'No active Tags available'}</option>{choices.filter(tag=>tag.lifecycle==='active'&&!assigned.some(row=>row.tag.id===tag.id)).map(tag=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><button className="button button--small button--cyan" disabled={busy||!tagId}>Assign Tag</button></form>{error&&<p className="inline-feedback" role="alert">{error}</p>}</section>
}
