import type { Concept, Tag, TagMatchMode, TimelineCategory, TimelineEntityKind, Workspace, WorkspacePanel, WorkspacePanelSort, WorkspacePanelType, WorkspacePanelVariant, WorkspaceTemplate } from '../../domain/world';
import { PANEL_REGISTRY } from './panelRegistry';

export type ConceptReference = { key:string; name:string; typeCode:string };
export type TagReference = { key:string; name:string };
export type TimelineEntityReference = { kind:TimelineEntityKind; label:'Specific local record' };
export type PortablePanel = Pick<WorkspacePanel,'panelType'|'title'|'variant'|'density'|'filterStatus'|'filterActive'|'filterTypeCode'|'filterTagMatch'|'filterRecentDays'|'filterTimelineCategory'|'filterTimelineEntityKind'|'filterTimelineFrom'|'filterTimelineThrough'|'sortBy'|'itemLimit'|'sortOrder'|'gridSpan'|'isVisible'|'isPinned'|'isCollapsed'> & {
 relatedConcept:ConceptReference|null; tagReferences:TagReference[]; timelineEntityIdentity:TimelineEntityReference|null;
};
export type PortableWorkspace={format:'life-rpg-workspace';version:4;workspace:{name:string;template:WorkspaceTemplate};panels:PortablePanel[]};
type V3Panel=Omit<PortablePanel,'tagReferences'|'filterTagMatch'>;
type V3Workspace={format:'life-rpg-workspace';version:3;workspace:PortableWorkspace['workspace'];panels:V3Panel[]};
type V2Panel=Pick<WorkspacePanel,'panelType'|'title'|'variant'|'density'|'filterStatus'|'filterActive'|'filterTypeCode'|'filterRecentDays'|'sortBy'|'itemLimit'|'sortOrder'|'gridSpan'|'isVisible'|'isPinned'|'isCollapsed'>&{relatedConcept:ConceptReference|null};
type V2Workspace={format:'life-rpg-workspace';version:2;workspace:PortableWorkspace['workspace'];panels:V2Panel[]};
export type WorkspaceImportPreview={portable:PortableWorkspace;references:{panelIndex:number;reference:ConceptReference;autoResolvedId:string|null;candidates:Concept[]}[];tagReferences:{panelIndex:number;tagIndex:number;reference:TagReference;autoResolvedId:string|null;candidates:Tag[]}[];legacyConceptPanels:number[];unresolvedTimelineIdentityPanels:number[]};
export type ResolvedWorkspaceImport={workspace:PortableWorkspace['workspace'];panels:(Omit<PortablePanel,'relatedConcept'|'tagReferences'|'timelineEntityIdentity'>&{filterConceptId:string|null;filterTagIds:string[];filterTimelineEntityId:string|null})[];resolvedConcepts:number;unresolvedConcepts:number;resolvedTags:number;unresolvedTags:number;unresolvedTimelineIdentities:number};

const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const exactKeys=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).every(key=>keys.includes(key))&&keys.every(key=>Object.hasOwn(value,key));
const nullableString=(value:unknown,max=160):value is string|null=>value===null||(typeof value==='string'&&value.length>0&&value.length<=max);
const templates:WorkspaceTemplate[]=['overview','focus','learning','health','review','custom'];
const timelineCategories:TimelineCategory[]=['session','transaction','effect_history','content','comment','concept_progress','revision','snapshot','record_change','lifecycle','relationship_history'];
const timelineEntityKinds:TimelineEntityKind[]=['player','concept','quest','quest_stage','quest_branch','quest_session','skill_tree','skill','effect','transaction','comment','narrative_entry','concept_progress'];
const conceptRefKeys=['key','name','typeCode'];
const tagRefKeys=['key','name'];
const v4Keys=['panelType','title','variant','density','filterStatus','filterActive','filterTypeCode','relatedConcept','filterTagMatch','tagReferences','filterRecentDays','filterTimelineCategory','filterTimelineEntityKind','filterTimelineFrom','filterTimelineThrough','timelineEntityIdentity','sortBy','itemLimit','sortOrder','gridSpan','isVisible','isPinned','isCollapsed'];
const v3Keys=v4Keys.filter(key=>key!=='filterTagMatch'&&key!=='tagReferences');
const v2Keys=['panelType','title','variant','density','filterStatus','filterActive','filterTypeCode','relatedConcept','filterRecentDays','sortBy','itemLimit','sortOrder','gridSpan','isVisible','isPinned','isCollapsed'];
const legacyPanelKeys=v2Keys.filter(key=>key!=='relatedConcept').concat('filterConceptId');
const normalizeName=(name:string)=>name.trim().normalize('NFKC').toLowerCase();

function validateConceptReference(value:unknown,panelNumber:number):ConceptReference|null{
 if(value===null)return null;
 if(!record(value)||!exactKeys(value,conceptRefKeys)||typeof value.key!=='string'||!/^concept-ref-[a-zA-Z0-9-]{8,112}$/.test(value.key)||typeof value.name!=='string'||!value.name.trim()||value.name.length>512||typeof value.typeCode!=='string'||!/^[a-z0-9_]{1,160}$/.test(value.typeCode))throw new Error(`Panel ${panelNumber} has an invalid Concept reference.`);
 return {key:value.key,name:value.name.trim(),typeCode:value.typeCode};
}
function validateTagReferences(value:unknown,panelNumber:number):TagReference[]{
 if(!Array.isArray(value)||value.length>20)throw new Error(`Panel ${panelNumber} has an invalid Tag reference list.`);
 const refs=value.map(item=>{if(!record(item)||!exactKeys(item,tagRefKeys)||typeof item.key!=='string'||!/^tag-ref-[a-zA-Z0-9_-]{1,120}$/.test(item.key)||typeof item.name!=='string'||!item.name.trim()||item.name.length>80)throw new Error(`Panel ${panelNumber} has an invalid Tag reference.`);return {key:item.key,name:item.name.trim()};});
 if(new Set(refs.map(ref=>ref.key)).size!==refs.length)throw new Error(`Panel ${panelNumber} contains duplicate Tag references.`);
 return refs;
}
function validateCommonPanel(raw:Record<string,unknown>,index:number,reference:ConceptReference|null,timeline:boolean,tagReferences:TagReference[],tagMatch:TagMatchMode):PortablePanel{
 const type=raw.panelType as WorkspacePanelType;const def=PANEL_REGISTRY[type];
 const category=timeline?raw.filterTimelineCategory:null, entityKind=timeline?raw.filterTimelineEntityKind:null, from=timeline?raw.filterTimelineFrom:null, through=timeline?raw.filterTimelineThrough:null, identity=timeline?raw.timelineEntityIdentity:null;
 if(!def||typeof raw.variant!=='string'||!def.variants.includes(raw.variant as WorkspacePanelVariant)||(raw.density!=='cozy'&&raw.density!=='compact')||(typeof raw.title!=='string'&&raw.title!==null)||(typeof raw.title==='string'&&(!raw.title.trim()||raw.title.length>120))||(raw.filterStatus!==null&&(typeof raw.filterStatus!=='string'||!def.statuses.includes(raw.filterStatus)))||(raw.filterActive!==null&&typeof raw.filterActive!=='boolean')||(raw.filterTypeCode!==null&&(!nullableString(raw.filterTypeCode)||!/^[a-z0-9_]{1,160}$/.test(raw.filterTypeCode)))||(raw.filterRecentDays!==null&&(!Number.isInteger(raw.filterRecentDays)||(raw.filterRecentDays as number)<1||(raw.filterRecentDays as number)>365))||typeof raw.sortBy!=='string'||!def.sorts.includes(raw.sortBy as WorkspacePanelSort)||!Number.isInteger(raw.itemLimit)||(raw.itemLimit as number)<1||(raw.itemLimit as number)>50||!Number.isInteger(raw.sortOrder)||(raw.sortOrder as number)<0||(raw.sortOrder as number)>999||![1,2].includes(raw.gridSpan as number)||typeof raw.isVisible!=='boolean'||typeof raw.isPinned!=='boolean'||typeof raw.isCollapsed!=='boolean')throw new Error(`Panel ${index+1} contains a value not allowed for its source.`);
 if((!def.supportsActive&&raw.filterActive!==null)||(!def.supportsType&&raw.filterTypeCode!==null)||(!def.supportsConcept&&reference!==null)||(!def.supportsRecent&&raw.filterRecentDays!==null)||(!def.supportsTags&&tagReferences.length>0))throw new Error(`Panel ${index+1} uses a filter unsupported by its source.`);
 if(tagMatch!=='any'&&tagMatch!=='all')throw new Error(`Panel ${index+1} has an invalid Tag matching mode.`);
 if(timeline){const validDate=(value:unknown)=>value===null||(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`)));
  if(type!=='timeline'&&(category!==null||entityKind!==null||from!==null||through!==null||identity!==null))throw new Error(`Panel ${index+1} uses Timeline filters unsupported by its source.`);
  if(category!==null&&(typeof category!=='string'||!timelineCategories.includes(category as TimelineCategory)))throw new Error(`Panel ${index+1} has an invalid Timeline category.`);
  if(entityKind!==null&&(typeof entityKind!=='string'||!timelineEntityKinds.includes(entityKind as TimelineEntityKind)))throw new Error(`Panel ${index+1} has an invalid Timeline entity kind.`);
  if(!validDate(from)||!validDate(through)||(from!==null&&through!==null&&(from as string)>(through as string)))throw new Error(`Panel ${index+1} has an invalid Timeline date range.`);
  if(identity!==null&&(!record(identity)||!exactKeys(identity,['kind','label'])||!timelineEntityKinds.includes(identity.kind as TimelineEntityKind)||identity.label!=='Specific local record'||identity.kind!==entityKind))throw new Error(`Panel ${index+1} has an invalid Timeline identity reference.`);
 }
 return {...raw,relatedConcept:reference,filterTagMatch:tagMatch,tagReferences,timelineEntityIdentity:identity as TimelineEntityReference|null} as PortablePanel;
}
function validateV4(value:unknown):PortableWorkspace{
 if(!record(value)||value.format!=='life-rpg-workspace')throw new Error('This file is not a Life RPG workspace export.');
 if(value.version!==4)throw new Error(`Workspace format version ${String(value.version)} is not supported.`);
 if(!exactKeys(value,['format','version','workspace','panels'])||!record(value.workspace)||!exactKeys(value.workspace,['name','template'])||typeof value.workspace.name!=='string'||!value.workspace.name.trim()||value.workspace.name.trim().length>80||typeof value.workspace.template!=='string'||!templates.includes(value.workspace.template as WorkspaceTemplate)||!Array.isArray(value.panels)||value.panels.length>100)throw new Error('The workspace export is malformed or exceeds supported limits.');
 const panels=value.panels.map((raw,index)=>{if(!record(raw)||!exactKeys(raw,v4Keys))throw new Error(`Panel ${index+1} has missing or unknown configuration fields.`);const concept=validateConceptReference(raw.relatedConcept,index+1);const tags=validateTagReferences(raw.tagReferences,index+1);return validateCommonPanel(raw,index,concept,true,tags,raw.filterTagMatch as TagMatchMode)});
 return {format:'life-rpg-workspace',version:4,workspace:{name:(value.workspace.name as string).trim(),template:value.workspace.template as WorkspaceTemplate},panels};
}
function validateV3(value:unknown):V3Workspace{
 if(!record(value)||value.format!=='life-rpg-workspace'||value.version!==3)throw new Error('This is not a supported version 3 workspace export.');
 if(!exactKeys(value,['format','version','workspace','panels'])||!record(value.workspace)||!exactKeys(value.workspace,['name','template'])||typeof value.workspace.name!=='string'||!value.workspace.name.trim()||value.workspace.name.trim().length>80||typeof value.workspace.template!=='string'||!templates.includes(value.workspace.template as WorkspaceTemplate)||!Array.isArray(value.panels)||value.panels.length>100)throw new Error('The workspace export is malformed or exceeds supported limits.');
 const panels=value.panels.map((raw,index)=>{if(!record(raw)||!exactKeys(raw,v3Keys))throw new Error(`Panel ${index+1} has missing or unknown configuration fields.`);const concept=validateConceptReference(raw.relatedConcept,index+1);const converted=validateCommonPanel({...raw,filterTagMatch:'any',tagReferences:[]},index,concept,true,[],'any');const {filterTagMatch:_mode,tagReferences:_tags,...legacy}=converted;return legacy as V3Panel});
 return {format:'life-rpg-workspace',version:3,workspace:{name:(value.workspace.name as string).trim(),template:value.workspace.template as WorkspaceTemplate},panels};
}
function upgradeV3(old:V3Workspace):PortableWorkspace{return validateV4({format:'life-rpg-workspace',version:4,workspace:old.workspace,panels:old.panels.map(panel=>({...panel,filterTagMatch:'any',tagReferences:[]}))});}
function validateV2(value:unknown):V2Workspace{
 if(!record(value)||value.format!=='life-rpg-workspace'||value.version!==2)throw new Error('This is not a supported version 2 workspace export.');
 if(!exactKeys(value,['format','version','workspace','panels'])||!record(value.workspace)||!exactKeys(value.workspace,['name','template'])||typeof value.workspace.name!=='string'||!value.workspace.name.trim()||value.workspace.name.trim().length>80||typeof value.workspace.template!=='string'||!templates.includes(value.workspace.template as WorkspaceTemplate)||!Array.isArray(value.panels)||value.panels.length>100)throw new Error('The workspace export is malformed or exceeds supported limits.');
 const panels=value.panels.map((raw,index)=>{if(!record(raw)||!exactKeys(raw,v2Keys))throw new Error(`Panel ${index+1} has missing or unknown configuration fields.`);const concept=validateConceptReference(raw.relatedConcept,index+1);const converted=validateCommonPanel({...raw,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineFrom:null,filterTimelineThrough:null,timelineEntityIdentity:null,filterTagMatch:'any',tagReferences:[]},index,concept,false,[],'any');const {filterTimelineCategory:_a,filterTimelineEntityKind:_b,filterTimelineFrom:_c,filterTimelineThrough:_d,timelineEntityIdentity:_e,filterTagMatch:_f,tagReferences:_g,...legacy}=converted;return legacy as V2Panel});
 return {format:'life-rpg-workspace',version:2,workspace:{name:(value.workspace.name as string).trim(),template:value.workspace.template as WorkspaceTemplate},panels};
}
function upgradeV2(value:unknown):PortableWorkspace{const old=validateV2(value);const v3={format:'life-rpg-workspace' as const,version:3 as const,workspace:old.workspace,panels:old.panels.map(panel=>({...panel,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineFrom:null,filterTimelineThrough:null,timelineEntityIdentity:null}))};return upgradeV3(validateV3(v3));}
function migrateV1(value:unknown):{portable:PortableWorkspace;legacyConceptPanels:number[]}{
 if(!record(value)||value.format!=='life-rpg-workspace'||value.version!==1)throw new Error('This is not a supported version 1 workspace export.');
 if(!exactKeys(value,['format','version','workspace','panels'])||!record(value.workspace)||!exactKeys(value.workspace,['name','template'])||!Array.isArray(value.panels)||value.panels.length>100)throw new Error('The legacy workspace export is malformed or exceeds supported limits.');
 const legacyConceptPanels:number[]=[];const panels=value.panels.map((raw,index)=>{if(!record(raw)||!exactKeys(raw,legacyPanelKeys)||!Object.hasOwn(raw,'filterConceptId')||(raw.filterConceptId!==null&&typeof raw.filterConceptId!=='string'))throw new Error(`Legacy panel ${index+1} contains unknown or invalid fields.`);if(raw.filterConceptId!==null)legacyConceptPanels.push(index);const {filterConceptId:_untrustedLocalId,...rest}=raw;const filterStatus=rest.panelType==='quests'&&rest.filterStatus==='in_progress'?'active':rest.panelType==='quests'&&rest.filterStatus==='pending'?'open':rest.panelType==='activity'&&rest.filterStatus==='active'?'in_progress':rest.filterStatus;return {...rest,filterStatus,relatedConcept:null}});
 const v2={format:'life-rpg-workspace',version:2,workspace:value.workspace,panels};const v2validated=validateV2(v2);const v3={format:'life-rpg-workspace' as const,version:3 as const,workspace:v2validated.workspace,panels:v2validated.panels.map(panel=>({...panel,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineFrom:null,filterTimelineThrough:null,timelineEntityIdentity:null}))};return {portable:upgradeV3(validateV3(v3)),legacyConceptPanels};
}
export function validateWorkspaceImport(value:unknown):PortableWorkspace{if(record(value)&&value.version===1)return migrateV1(value).portable;if(record(value)&&value.version===2)return upgradeV2(value);if(record(value)&&value.version===3)return upgradeV3(validateV3(value));return validateV4(value)}
export function previewWorkspaceImport(value:unknown,concepts:Concept[],tags:Tag[]=[]):WorkspaceImportPreview{
 let portable:PortableWorkspace;let legacyConceptPanels:number[]=[];if(record(value)&&value.version===1){const migrated=migrateV1(value);portable=migrated.portable;legacyConceptPanels=migrated.legacyConceptPanels}else portable=validateWorkspaceImport(value);
 const references:WorkspaceImportPreview['references']=[];const tagReferences:WorkspaceImportPreview['tagReferences']=[];const unresolvedTimelineIdentityPanels:number[]=[];
 portable.panels.forEach((panel,panelIndex)=>{if(panel.timelineEntityIdentity)unresolvedTimelineIdentityPanels.push(panelIndex);if(panel.relatedConcept){const reference=panel.relatedConcept;const exact=concepts.filter(concept=>concept.transferKey===reference.key&&concept.typeCode===reference.typeCode);const candidates=[...new Map([...exact,...concepts.filter(concept=>concept.typeCode===reference.typeCode&&normalizeName(concept.name)===normalizeName(reference.name))].map(concept=>[concept.id,concept])).values()];references.push({panelIndex,reference,autoResolvedId:exact.length===1?exact[0]!.id:null,candidates})}panel.tagReferences.forEach((reference,tagIndex)=>{const exact=tags.filter(tag=>tag.transferKey===reference.key);const candidates=[...new Map([...exact,...tags.filter(tag=>normalizeName(tag.name)===normalizeName(reference.name))].map(tag=>[tag.id,tag])).values()];tagReferences.push({panelIndex,tagIndex,reference,autoResolvedId:exact.length===1&&exact[0]!.lifecycle==='active'?exact[0]!.id:null,candidates})})});
 return {portable,references,tagReferences,legacyConceptPanels,unresolvedTimelineIdentityPanels};
}
export function resolveWorkspaceImport(preview:WorkspaceImportPreview,selections:Record<number,string>,concepts:Concept[],tagSelections:Record<string,string>={}):ResolvedWorkspaceImport{
 const conceptRefs=new Map(preview.references.map(reference=>[reference.panelIndex,reference]));const tagRefs=new Map(preview.tagReferences.map(reference=>[`${reference.panelIndex}:${reference.tagIndex}`,reference]));let resolvedConcepts=0,unresolvedConcepts=preview.legacyConceptPanels.length,resolvedTags=0,unresolvedTags=0;
 const panels=preview.portable.panels.map((panel,panelIndex)=>{const conceptRef=conceptRefs.get(panelIndex);let filterConceptId:string|null=null;if(conceptRef){const selected=selections[panelIndex];if(conceptRef.autoResolvedId)filterConceptId=selected===undefined?conceptRef.autoResolvedId:selected||null;else if(selected)filterConceptId=selected;if(filterConceptId&&!conceptRef.candidates.some(candidate=>candidate.id===filterConceptId))throw new Error(`Panel ${panelIndex+1} selected a Concept that was not offered by the preview.`);if(filterConceptId&&!concepts.some(concept=>concept.id===filterConceptId))throw new Error(`Panel ${panelIndex+1} references a Concept outside this Player world.`);if(filterConceptId)resolvedConcepts++;else unresolvedConcepts++}
  const filterTagIds:string[]=[];panel.tagReferences.forEach((_,tagIndex)=>{const previewRef=tagRefs.get(`${panelIndex}:${tagIndex}`)!;const selection=tagSelections[`${panelIndex}:${tagIndex}`];const chosen=previewRef.autoResolvedId?(selection===undefined?previewRef.autoResolvedId:selection||null):(selection||null);if(chosen&&!previewRef.candidates.some(candidate=>candidate.id===chosen&&candidate.lifecycle==='active'))throw new Error(`Panel ${panelIndex+1} selected a Tag that was not offered as active in this Player world.`);if(chosen){filterTagIds.push(chosen);resolvedTags++}else unresolvedTags++});
  const {relatedConcept:_concept,tagReferences:_tagRefs,timelineEntityIdentity:_identity,filterTagMatch,...configuration}=panel;return {...configuration,filterConceptId,filterTagIds,filterTagMatch:panel.filterTagMatch,filterTimelineEntityId:null};});
 return {workspace:preview.portable.workspace,panels,resolvedConcepts,unresolvedConcepts,resolvedTags,unresolvedTags,unresolvedTimelineIdentities:preview.unresolvedTimelineIdentityPanels.length};
}
export function exportWorkspace(workspace:Workspace,panels:WorkspacePanel[],concepts:Concept[],tags:Tag[]=[]):PortableWorkspace{
 const conceptsById=new Map(concepts.filter(concept=>concept.playerId===workspace.playerId).map(concept=>[concept.id,concept]));const tagsById=new Map(tags.filter(tag=>tag.playerId===workspace.playerId&&tag.lifecycle==='active').map(tag=>[tag.id,tag]));
 const portablePanels=panels.map(({panelType,title,variant,density,filterStatus,filterActive,filterTypeCode,filterConceptId,filterTagIds,filterTagMatch,filterRecentDays,filterTimelineCategory,filterTimelineEntityKind,filterTimelineEntityId,filterTimelineFrom,filterTimelineThrough,sortBy,itemLimit,sortOrder,gridSpan,isVisible,isPinned,isCollapsed})=>{
  const concept=filterConceptId?conceptsById.get(filterConceptId):undefined;if(filterConceptId&&!concept)throw new Error('A panel Concept filter is not available in this workspace Player world.');
  if(filterTimelineEntityId&&!filterTimelineEntityKind)throw new Error('A Timeline exact identity filter requires an entity kind.');
  if(filterTagIds.length>20||new Set(filterTagIds).size!==filterTagIds.length)throw new Error('A panel Tag filter contains too many or duplicate Tags.');
  const references=filterTagIds.map(id=>{const tag=tagsById.get(id);if(!tag)throw new Error('A panel Tag filter is not available as an active Tag in this workspace Player world.');return {key:tag.transferKey,name:tag.name}});
  return {panelType,title,variant,density,filterStatus,filterActive,filterTypeCode,relatedConcept:concept?{key:concept.transferKey,name:concept.name,typeCode:concept.typeCode}:null,filterTagMatch,tagReferences:references,filterRecentDays,filterTimelineCategory,filterTimelineEntityKind,filterTimelineFrom,filterTimelineThrough,timelineEntityIdentity:filterTimelineEntityId?{kind:filterTimelineEntityKind!,label:'Specific local record' as const}:null,sortBy,itemLimit,sortOrder,gridSpan,isVisible,isPinned,isCollapsed};
 });
 const stablePanels=portablePanels.sort((a,b)=>a.sortOrder-b.sortOrder||JSON.stringify(a).localeCompare(JSON.stringify(b)));
 return validateV4({format:'life-rpg-workspace',version:4,workspace:{name:workspace.name,template:workspace.template},panels:stablePanels});
}
