import { afterEach,describe,expect,it,vi } from 'vitest';
import { act,cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { AppShell,type AppRoute } from '../app/AppShell';
import type { CoreClient } from '../domain/ipc';
import type { Concept,EntityRevision,Player,Quest,QuestBranch,QuestStage,SearchHit,Skill,SkillTree,WorldOverview } from '../domain/world';
import { WorldWorkspace } from '../features/world/WorldWorkspace';
import { PlayerCharacter } from '../features/world/PlayerCharacter';
import { WorldExplorer } from '../features/world/WorldExplorer';

afterEach(()=>{cleanup();localStorage.clear();vi.restoreAllMocks();});
const player:Player={id:'player-1',name:'Rin',description:'A test world',level:3,levelName:'Wayfinder',progressionLabel:'Mapping the unknown',currentXp:920,isActive:true,metadataJson:'{}',createdAt:'2026-09-20T00:00:00Z',updatedAt:'2026-09-27T00:00:00Z'};
const quest:Quest={id:'quest-1',playerId:player.id,typeCode:'main',parentQuestId:null,skillId:null,title:'Prepare the garden',status:'active',difficulty:null,progress:25,xpReward:0,dueAt:null,startedAt:'2026-09-27T08:00:00Z',completedAt:null,description:'A small real-world objective'};
const tree:SkillTree={id:'tree-1',playerId:player.id,typeCode:'life',name:'Daily practice',description:null,isActive:true};
const skill:Skill={id:'skill-1',skillTreeId:tree.id,parentSkillId:null,typeCode:'core',name:'Observation',story:null,instructions:null,level:2,levelName:'Attentive',progressionLabel:'Player-authored',currentXp:700,investedMinutes:35,status:'active',availability:'available',availabilityControl:'manual'};
const concept:Concept={id:'concept-1',playerId:player.id,transferKey:'concept-ref-v1-garden-key',typeCode:'project',name:'Garden',description:null,isActive:true,metadataJson:'{}',createdAt:'2026-09-20T00:00:00Z',updatedAt:'2026-09-27T00:00:00Z'};
const overview:WorldOverview={player,quests:[quest],skillTrees:[tree],skills:[skill],effects:[],recentTransactions:[],narratives:[]};
function mockClient(overrides:Record<string,unknown>={}):CoreClient{return {listPresentationPreferences:vi.fn(async()=>[]),listStatDefinitions:vi.fn(async()=>[]),listPlayerSnapshots:vi.fn(async()=>[]),searchWorld:vi.fn(async()=>[]),listQuestStages:vi.fn(async()=>[]),listQuestBranches:vi.fn(async()=>[]),listConceptProgress:vi.fn(async()=>[]),queryTimeline:vi.fn(async()=>[]),...overrides} as unknown as CoreClient;}

describe('Phase 4 world workspace',()=>{
 it('navigates to first-class Player, Skill Tree, and History destinations in the persistent shell',()=>{const onNavigate=vi.fn<(route:AppRoute)=>void>();render(<AppShell route="dashboard" onNavigate={onNavigate} player={player} players={[{id:player.id,name:player.name}]} onPlayerChange={()=>{}} workspaces={[]} workspace={null} onWorkspaceChange={()=>{}} onCreate={()=>{}} onQuickCapture={()=>{}} ready><div>Workspace</div></AppShell>);fireEvent.click(screen.getByRole('button',{name:/Player/}));expect(onNavigate).toHaveBeenCalledWith('player');fireEvent.click(screen.getByRole('button',{name:/Skill trees/}));expect(onNavigate).toHaveBeenCalledWith('skillTrees');fireEvent.click(screen.getByRole('button',{name:/History & recovery/}));expect(onNavigate).toHaveBeenCalledWith('history');});

	 it('keeps a hidden Skill out of its context, reports it, and can reveal it without altering the Skill',async()=>{const setPresentationVisibility=vi.fn(async()=>{});const client=mockClient({setPresentationVisibility,listPresentationPreferences:vi.fn(async()=>[{playerId:player.id,entityKind:'skill',entityId:skill.id,context:'skills',isVisible:false,isPinned:false,isCollapsed:null,sortOrder:0,variant:null,density:null,metadataJson:'{}',createdAt:'',updatedAt:''}])});render(<WorldWorkspace route="skills" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={null} panels={[]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);expect(await screen.findByText('1 hidden item')).toBeInTheDocument();expect(screen.queryByText('Observation')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Reveal hidden items'}));expect(await screen.findByText('Observation')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Show in this context'}));await waitFor(()=>expect(setPresentationVisibility).toHaveBeenCalledWith(expect.objectContaining({entityKind:'skill',entityId:skill.id,context:'skills',isVisible:true})));expect(skill.level).toBe(2);});

 it('persists dashboard collapse, pin, and layout through the workspace panel API',async()=>{const workspace={id:'workspace-1',playerId:player.id,name:'Overview',template:'overview' as const,sortOrder:0,isDefault:true,createdAt:'',updatedAt:''};const panel={id:'panel-quests',workspaceId:workspace.id,panelType:'quests' as const,title:'Quest board',variant:'cards' as const,density:'cozy' as const,filterStatus:null,filterActive:null,filterTypeCode:null,filterConceptId:null,filterRecentDays:null,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineEntityId:null,filterTimelineFrom:null,filterTimelineThrough:null,sortBy:'updated_desc' as const,itemLimit:6,sortOrder:0,gridSpan:1,isVisible:true,isPinned:true,isCollapsed:false,createdAt:'',updatedAt:''};const saveWorkspacePanel=vi.fn(async(v:Record<string,unknown>)=>({...v,id:panel.id,workspaceId:workspace.id,createdAt:'',updatedAt:''}));const onPanelsChange=vi.fn();const client=mockClient({saveWorkspacePanel,listStatDefinitions:vi.fn(async()=>[])});render(<WorldWorkspace route="dashboard" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={workspace} panels={[panel]} onPanelsChange={onPanelsChange} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Collapse panel'}));await waitFor(()=>expect(saveWorkspacePanel).toHaveBeenCalledWith(expect.objectContaining({workspaceId:workspace.id,panelId:panel.id,panelType:'quests',isPinned:true,isCollapsed:true,sortOrder:0})));expect(localStorage.getItem('life-rpg.dashboard-panels.v1')).toBeNull();expect(quest.status).toBe('active');});

 it('persists a bounded status filter selected in the Workspace Builder',async()=>{const workspace={id:'workspace-1',playerId:player.id,name:'Learning',template:'learning' as const,sortOrder:0,isDefault:false,createdAt:'',updatedAt:''};const panel={id:'panel-quests',workspaceId:workspace.id,panelType:'quests' as const,title:'Quest board',variant:'cards' as const,density:'cozy' as const,filterStatus:null,filterActive:null,filterTypeCode:null,filterConceptId:null,filterRecentDays:null,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineEntityId:null,filterTimelineFrom:null,filterTimelineThrough:null,sortBy:'updated_desc' as const,itemLimit:6,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false,createdAt:'',updatedAt:''};const saveWorkspacePanel=vi.fn(async(v:Record<string,unknown>)=>({...v,id:panel.id,workspaceId:workspace.id,createdAt:'',updatedAt:''}));const client=mockClient({saveWorkspacePanel});render(<WorldWorkspace route="dashboard" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={workspace} panels={[panel]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Customize workspace'}));fireEvent.change(await screen.findByLabelText('Status'),{target:{value:'active'}});fireEvent.click(screen.getByRole('button',{name:'Save panel'}));await waitFor(()=>expect(saveWorkspacePanel).toHaveBeenCalledWith(expect.objectContaining({playerId:player.id,workspaceId:workspace.id,panelId:panel.id,filterStatus:'active'})));});
 it('allows multiple independently configurable instances of the same panel source',async()=>{const workspace={id:'workspace-1',playerId:player.id,name:'Learning',template:'learning' as const,sortOrder:0,isDefault:false,createdAt:'',updatedAt:''};const panel={id:'panel-quests',workspaceId:workspace.id,panelType:'quests' as const,title:'In progress',variant:'cards' as const,density:'cozy' as const,filterStatus:'active',filterActive:null,filterTypeCode:null,filterConceptId:null,filterRecentDays:null,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineEntityId:null,filterTimelineFrom:null,filterTimelineThrough:null,sortBy:'updated_desc' as const,itemLimit:6,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false,createdAt:'',updatedAt:''};const saveWorkspacePanel=vi.fn(async(v:Record<string,unknown>)=>({...v,id:v.panelId??'panel-quests-2',workspaceId:workspace.id,createdAt:'',updatedAt:''}));const onPanelsChange=vi.fn();const client=mockClient({saveWorkspacePanel});render(<WorldWorkspace route="dashboard" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={workspace} panels={[panel]} onPanelsChange={onPanelsChange} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Customize workspace'}));fireEvent.click(screen.getByRole('button',{name:/Add panel/}));await waitFor(()=>expect(saveWorkspacePanel).toHaveBeenCalledWith(expect.objectContaining({workspaceId:workspace.id,panelType:'quests',sortOrder:1,variant:'cards'})));expect(onPanelsChange).toHaveBeenCalledWith(expect.arrayContaining([expect.objectContaining({id:panel.id,filterStatus:'active'}),expect.objectContaining({id:'panel-quests-2',filterStatus:null})]));});
 it('previews a workspace transfer and waits for an explicit confirm before atomic import',async()=>{const workspace={id:'workspace-1',playerId:player.id,name:'Learning',template:'learning' as const,sortOrder:0,isDefault:false,createdAt:'',updatedAt:''};const panel={id:'panel-1',workspaceId:workspace.id,panelType:'quests' as const,title:'Garden quests',variant:'cards' as const,density:'cozy' as const,filterStatus:'active',filterActive:null,filterTypeCode:null,filterConceptId:concept.id,filterRecentDays:null,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineEntityId:null,filterTimelineFrom:null,filterTimelineThrough:null,sortBy:'updated_desc' as const,itemLimit:6,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false,createdAt:'',updatedAt:''};const importWorkspace=vi.fn(async()=>{});const client=mockClient();render(<WorldWorkspace route="dashboard" client={client} player={player} overview={overview} concepts={[concept]} stats={[]} sessions={[]} workspace={workspace} panels={[panel]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[workspace]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={importWorkspace} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Customize workspace'}));const portable={format:'life-rpg-workspace',version:2,workspace:{name:'Learning',template:'learning'},panels:[{panelType:'quests',title:'Garden quests',variant:'cards',density:'cozy',filterStatus:'active',filterActive:null,filterTypeCode:null,relatedConcept:{key:concept.transferKey,name:concept.name,typeCode:concept.typeCode},filterRecentDays:null,sortBy:'updated_desc',itemLimit:6,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false}]};const file=new File([JSON.stringify(portable)],'learning.json',{type:'application/json'});Object.defineProperty(file,'text',{value:async()=>JSON.stringify(portable)});fireEvent.change(screen.getByLabelText('Preview import'),{target:{files:[file]}});expect(await screen.findByRole('heading',{name:/Review import/})).toBeInTheDocument();expect(importWorkspace).not.toHaveBeenCalled();expect(await screen.findByText('Exact stable-key match in this world.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Import reviewed workspace'}));await waitFor(()=>expect(importWorkspace).toHaveBeenCalledWith(expect.objectContaining({resolvedConcepts:1,unresolvedConcepts:0,panels:[expect.objectContaining({filterConceptId:concept.id})]})));});
 it('creates directed Concept relationships using the typed backend relationship vocabulary',async()=>{const target={...concept,id:'concept-2',name:'Gardening'};const relateConcepts=vi.fn(async()=>({}));const client=mockClient({listConceptRelationshipTypes:vi.fn(async()=>['related_to','depends_on']),listConceptRelationships:vi.fn(async()=>[]),listConceptProgress:vi.fn(async()=>[]),relateConcepts});render(<WorldWorkspace route="concepts" client={client} player={player} overview={overview} concepts={[concept,target]} stats={[]} sessions={[]} workspace={null} panels={[]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.change((await screen.findAllByLabelText('Related Concept'))[0]!,{target:{value:target.id}});fireEvent.click(screen.getAllByRole('button',{name:'Relate'})[0]!);await waitFor(()=>expect(relateConcepts).toHaveBeenCalledWith(concept.id,target.id,'related_to'));});

 it('passes hidden inclusion as an explicit search filter rather than changing the hidden record',async()=>{const searchWorld=vi.fn(async()=>[]);const client=mockClient({searchWorld});render(<WorldExplorer client={client} player={player} concepts={[concept]} overview={overview} onRefresh={async()=>{}}/>);await waitFor(()=>expect(searchWorld).toHaveBeenCalled());fireEvent.click(screen.getByRole('checkbox',{name:'include hidden'}));fireEvent.click(screen.getByRole('button',{name:'Search world'}));await waitFor(()=>expect(searchWorld).toHaveBeenLastCalledWith(expect.objectContaining({includeHidden:true,context:'explorer'})));expect(skill.level).toBe(2);});

 it('saves Player level as explicit authored state without deriving it from XP',async()=>{const setPlayerProgression=vi.fn(async()=>player);const client=mockClient({setPlayerProgression,listStatDefinitions:vi.fn(async()=>[]),listPlayerSnapshots:vi.fn(async()=>[])});render(<PlayerCharacter client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} tracks={{}} onRefresh={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}} />);fireEvent.click(screen.getByRole('button',{name:'Edit progression'}));const input=screen.getByLabelText('Level');fireEvent.change(input,{target:{value:'4'}});fireEvent.click(screen.getByRole('button',{name:'Save authored level'}));await waitFor(()=>expect(setPlayerProgression).toHaveBeenCalledWith(player.id,4,'Wayfinder','Mapping the unknown'));expect(player.currentXp).toBe(920);});

	 it('starts a branch Session under its Quest Stage with a real start timestamp delegated to the command',async()=>{const stage:QuestStage={id:'stage-1',playerId:player.id,questId:quest.id,title:'Prepare',description:null,story:null,instructions:null,status:'active',sortOrder:0,isActive:true,metadataJson:'{}',createdAt:'',updatedAt:''};const branch:QuestBranch={id:'branch-1',playerId:player.id,questId:quest.id,stageId:stage.id,title:'Clear the bed',description:null,status:'active',sortOrder:0,isActive:true,metadataJson:'{}',createdAt:'',updatedAt:''};const startQuestSession=vi.fn(async()=>({}));const client=mockClient({listQuestStages:vi.fn(async()=>[stage]),listQuestBranches:vi.fn(async()=>[branch]),listQuestSessions:vi.fn(async()=>[]),listAttachedContent:vi.fn(async()=>[]),startQuestSession});render(<WorldWorkspace route="quests" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={null} panels={[]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Stages & activity'}));fireEvent.click(await screen.findByRole('button',{name:'Start branch session'}));await waitFor(()=>expect(startQuestSession).toHaveBeenCalledWith(player.id,{questId:quest.id,stageId:stage.id,branchId:branch.id}));});

	 it('does not expose or call context-free Session creation on the Quest page',async()=>{const startQuestSession=vi.fn(async()=>({}));const client=mockClient({startQuestSession,listStatDefinitions:vi.fn(async()=>[])});render(<WorldWorkspace route="quests" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={null} panels={[]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);await act(async()=>{await Promise.resolve();});expect(screen.queryByRole('button',{name:/start a focus session/i})).not.toBeInTheDocument();expect(startQuestSession).not.toHaveBeenCalled();expect(screen.getByRole('status')).toHaveTextContent(/Start one from a Quest, Stage, Branch, or Skill/);});

	 it('forwards the Quest description entered in the creation form',async()=>{const createQuest=vi.fn(async()=>quest);const client=mockClient({createQuest,listPresentationPreferences:vi.fn(async()=>[])});render(<WorldWorkspace route="quests" client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} workspace={null} panels={[]} onPanelsChange={()=>{}} onCreateWorkspace={async()=>{}} onRenameWorkspace={async()=>{}} workspaces={[]} onDefaultWorkspace={async()=>{}} onDeleteWorkspace={async()=>{}} onDuplicateWorkspace={async()=>{}} onImportWorkspace={async()=>{}} onRefresh={async()=>{}} onCreatePlayer={async()=>{}} onNavigate={()=>{}} onOpenEntity={()=>{}} onQuickCapture={()=>{}}/>);fireEvent.change(screen.getByLabelText('Title'),{target:{value:'Prepare the garden'}});fireEvent.change(screen.getByLabelText(/Context/),{target:{value:'Prepare soil and water seedlings.'}});fireEvent.click(screen.getByRole('button',{name:'Add quest'}));await waitFor(()=>expect(createQuest).toHaveBeenCalledWith(player.id,'main','Prepare the garden',{description:'Prepare soil and water seedlings.',xpReward:0}));});

 it('shows hidden/trashed records in recovery search and restores a revision without erasing history',async()=>{const hit:SearchHit={kind:'quest',id:quest.id,playerId:player.id,conceptId:null,typeCode:'main',status:'active',active:true,lifecycle:'trashed',visible:false,occurredAt:quest.startedAt,capturedAt:null,name:quest.title,snippet:'garden objective',progression:25,relevance:null};const revision:EntityRevision={id:'revision-1',playerId:player.id,targetKind:'quest',targetId:quest.id,revisionNumber:2,recordedAt:'2026-09-27T12:00:00Z',authorPlayerId:player.id,reason:'Before restore',snapshotJson:'{"title":"Prepare the garden"}',metadataJson:'{}'};const searchWorld=vi.fn(async()=>[hit]);const restoreEntityRevision=vi.fn(async()=>revision);const client=mockClient({searchWorld,getEntityLifecycle:vi.fn(async()=>({state:'trashed' as const})),listPresentationPreferences:vi.fn(async()=>[]),listEntityRevisions:vi.fn(async()=>[revision]),listConceptAssociations:vi.fn(async()=>[]),listAttachedContent:vi.fn(async()=>[]),listComments:vi.fn(async()=>[]),listProgressSuggestions:vi.fn(async()=>[]),restoreEntityRevision});render(<WorldExplorer client={client} player={player} concepts={[concept]} overview={overview} onRefresh={async()=>{}} showRecovery/>);await screen.findByRole('button',{name:/Prepare the garden/});expect(searchWorld).toHaveBeenCalledWith(expect.objectContaining({includeArchived:true,includeTrashed:true}));fireEvent.click(screen.getByRole('button',{name:/Prepare the garden/}));expect(await screen.findByText('Before restore')).toBeInTheDocument();vi.spyOn(window,'confirm').mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Restore'}));await waitFor(()=>expect(restoreEntityRevision).toHaveBeenCalledWith(revision.id,'Restored in World Explorer'));expect(await screen.findByRole('status')).toHaveTextContent('pre-restore state remains in history');});
});


describe('Player Hub Timeline navigation', () => {
  it('links the preserved contextual activity list to the full Timeline', async () => {
    const onNavigate = vi.fn();
    const client = mockClient();
    render(<PlayerCharacter client={client} player={player} overview={overview} concepts={[]} stats={[]} sessions={[]} tracks={{}} onRefresh={async () => {}} onNavigate={onNavigate} onOpenEntity={() => {}} onQuickCapture={() => {}} />);
    expect(await screen.findByText('No recorded activity yet')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'View full timeline →' }));
    expect(onNavigate).toHaveBeenCalledWith('timeline');
  });
});
