import { describe, expect, it } from 'vitest';
import type { Concept, Workspace, WorkspacePanel } from '../domain/world';
import { exportWorkspace, previewWorkspaceImport, resolveWorkspaceImport, validateWorkspaceImport, type PortableWorkspace } from '../features/workspaces/workspaceTransfer';

const base=(panelType:'quests'|'timeline'='quests')=>({panelType,title:'Current',variant:panelType==='timeline'?'timeline':'cards',density:'cozy',filterStatus:null,filterActive:null,filterTypeCode:null,relatedConcept:null,filterRecentDays:null,filterTimelineCategory:panelType==='timeline'?'session':null,filterTimelineEntityKind:panelType==='timeline'?'quest_session':null,filterTimelineFrom:panelType==='timeline'?'2026-09-01':null,filterTimelineThrough:panelType==='timeline'?'2026-09-30':null,timelineEntityIdentity:null,sortBy:panelType==='timeline'?'timeline_newest':'updated_desc',itemLimit:8,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false});
const portable=():PortableWorkspace=>({format:'life-rpg-workspace',version:3,workspace:{name:'Python Learning',template:'learning'},panels:[{...base('timeline'),relatedConcept:{key:'concept-ref-v1-key-12345678',name:'Python',typeCode:'subject'},timelineEntityIdentity:{kind:'quest_session',label:'Specific local record'}},{...base('quests'),title:'Completed goals',filterStatus:'completed',filterTypeCode:null,relatedConcept:null,sortOrder:1}] as PortableWorkspace['panels']});
const concept=(id:string,playerId:string,transferKey:string,name='Python',typeCode='subject'):Concept=>({id,playerId,transferKey,typeCode,name,description:null,isActive:true,metadataJson:'{}',createdAt:'created',updatedAt:'updated'});
const workspace:Workspace={id:'workspace-local',playerId:'player-A',name:'Python Learning',template:'learning',sortOrder:0,isDefault:true,createdAt:'created',updatedAt:'updated'};
const panel=(filterConceptId:string|null,sortOrder:number):WorkspacePanel=>({id:`panel-${sortOrder}`,workspaceId:workspace.id,panelType:'quests',title:'Current',variant:'cards',density:'cozy',filterStatus:'active',filterActive:null,filterTypeCode:null,filterConceptId,filterRecentDays:30,filterTimelineCategory:null,filterTimelineEntityKind:null,filterTimelineEntityId:null,filterTimelineFrom:null,filterTimelineThrough:null,sortBy:'updated_desc',itemLimit:8,sortOrder,gridSpan:2,isVisible:true,isPinned:true,isCollapsed:false,createdAt:'created',updatedAt:'updated'});

describe('workspace transfer integrity',()=>{
  it('accepts strict version 3 Timeline filters alongside repeated independently configurable sources',()=>{const result=validateWorkspaceImport(portable());expect(result.version).toBe(3);expect(result.panels).toHaveLength(2);expect(result.panels[0]).toMatchObject({filterTimelineCategory:'session',filterTimelineEntityKind:'quest_session',filterTimelineFrom:'2026-09-01',filterTimelineThrough:'2026-09-30',timelineEntityIdentity:{kind:'quest_session'}})});
  it('exports presentation configuration deterministically without local IDs or timestamps',()=>{const timeline={...panel('concept-A',1),panelType:'timeline' as const,variant:'timeline' as const,filterStatus:null,filterRecentDays:null,filterTimelineCategory:'session' as const,filterTimelineEntityKind:'quest_session' as const,filterTimelineEntityId:'source-session-private-id',filterTimelineFrom:'2026-09-01',filterTimelineThrough:'2026-09-30',sortBy:'timeline_oldest' as const};const value=exportWorkspace(workspace,[timeline,{...panel(null,0),title:'First'}],[concept('concept-A','player-A','concept-ref-v1-key-12345678')]);const again=exportWorkspace(workspace,[timeline,{...panel(null,0),title:'First'}],[concept('concept-A','player-A','concept-ref-v1-key-12345678')]);expect(value).toEqual(again);expect(value.version).toBe(3);expect(value.panels[1]).toMatchObject({filterTimelineCategory:'session',filterTimelineEntityKind:'quest_session',filterTimelineFrom:'2026-09-01',filterTimelineThrough:'2026-09-30',timelineEntityIdentity:{kind:'quest_session'}});const json=JSON.stringify(value);for(const forbidden of ['player-A','concept-A','workspace-local','panel-0','createdAt','updatedAt','filterConceptId','source-session-private-id'])expect(json).not.toContain(forbidden)});
  it('preserves strict Concept-only cross-world matching while marking exact Timeline identities unresolved',()=>{const preview=previewWorkspaceImport(portable(),[concept('destination-id','player-B','concept-ref-v1-key-12345678')]);expect(preview.references[0]?.autoResolvedId).toBe('destination-id');expect(preview.unresolvedTimelineIdentityPanels).toEqual([0]);const result=resolveWorkspaceImport(preview,{},[concept('destination-id','player-B','concept-ref-v1-key-12345678')]);expect(result.panels[0]).toMatchObject({filterConceptId:'destination-id',filterTimelineEntityId:null,filterTimelineCategory:'session'});expect(result.unresolvedTimelineIdentities).toBe(1)});
  it('upgrades version 2 files with no Timeline filters into version 3 without relaxing strict validation',()=>{const v2={format:'life-rpg-workspace',version:2,workspace:{name:'Legacy v2',template:'learning'},panels:[{panelType:'quests',title:'Goals',variant:'cards',density:'cozy',filterStatus:null,filterActive:null,filterTypeCode:null,relatedConcept:null,filterRecentDays:null,sortBy:'updated_desc',itemLimit:8,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false}]};const preview=previewWorkspaceImport(v2,[]);expect(preview.portable.version).toBe(3);expect(preview.portable.panels[0]).toMatchObject({filterTimelineCategory:null,timelineEntityIdentity:null})});
  it('migrates version 1 files and discards source-local Concept IDs explicitly',()=>{const {relatedConcept:_unused,...legacyPanel}=base('quests') as any;delete legacyPanel.filterTimelineCategory;delete legacyPanel.filterTimelineEntityKind;delete legacyPanel.filterTimelineFrom;delete legacyPanel.filterTimelineThrough;delete legacyPanel.timelineEntityIdentity;const old={format:'life-rpg-workspace',version:1,workspace:{name:'Legacy',template:'learning'},panels:[{...legacyPanel,filterStatus:'in_progress',filterConceptId:'source-local-id'}]};const preview=previewWorkspaceImport(old,[]);expect(preview.portable.version).toBe(3);expect(preview.portable.panels[0]?.relatedConcept).toBeNull();expect(preview.portable.panels[0]?.filterStatus).toBe('active');expect(preview.legacyConceptPanels).toEqual([0]);expect(resolveWorkspaceImport(preview,{},[]).unresolvedConcepts).toBe(1)});
  it('rejects unknown versions, unknown fields, unsupported Timeline source filters, bad date ranges, and malformed identity descriptors',()=>{expect(()=>validateWorkspaceImport({...portable(),version:99})).toThrow(/not supported/);const extra=portable() as any;extra.panels[0].run='code';expect(()=>validateWorkspaceImport(extra)).toThrow(/unknown configuration fields/);const badSource=portable() as any;badSource.panels[1].filterTimelineCategory='session';expect(()=>validateWorkspaceImport(badSource)).toThrow(/unsupported by its source/);const badDate=portable() as any;badDate.panels[0].filterTimelineFrom='2026-10-01';expect(()=>validateWorkspaceImport(badDate)).toThrow(/date range/);const badIdentity=portable() as any;badIdentity.panels[0].timelineEntityIdentity={kind:'quest',id:'local-id'};expect(()=>validateWorkspaceImport(badIdentity)).toThrow(/identity reference/)});
  it('rejects forged local Concept references and preserves explicit candidate selection',()=>{const value=portable() as any;value.panels[0].relatedConcept={key:'player-A/internal-id',name:'Python',typeCode:'subject'};expect(()=>validateWorkspaceImport(value)).toThrow(/invalid Concept reference/);const preview=previewWorkspaceImport(portable(),[concept('similar','player-C','concept-ref-v1-other-key')]);expect(preview.references[0]?.autoResolvedId).toBeNull();expect(resolveWorkspaceImport(preview,{},[concept('similar','player-C','concept-ref-v1-other-key')]).panels[0]?.filterConceptId).toBeNull()});
});
