import { describe, expect, it } from 'vitest';
import type { Workspace, WorkspacePanel } from '../domain/world';
import { exportWorkspace, validateWorkspaceImport } from '../features/workspaces/workspaceTransfer';

const base=(panelType:'quests'|'skills'='quests')=>({panelType,title:'Current',variant:panelType==='skills'?'tree':'cards',density:'cozy',filterStatus:panelType==='quests'?'active':'active',filterActive:null,filterTypeCode:'main',filterConceptId:null,filterRecentDays:30,sortBy:panelType==='quests'?'updated_desc':'level_desc',itemLimit:8,sortOrder:0,gridSpan:1,isVisible:true,isPinned:false,isCollapsed:false});
const portable=()=>({format:'life-rpg-workspace',version:1,workspace:{name:'Python Learning',template:'learning'},panels:[base('quests'),{...base('quests'),title:'Completed goals',filterStatus:'completed',sortBy:'created_desc',sortOrder:1}]});

describe('workspace configuration import/export',()=>{
 it('accepts versioned declarative exports with repeated sources and independent filters',()=>{const result=validateWorkspaceImport(portable());expect(result.panels).toHaveLength(2);expect(result.panels[0]?.panelType).toBe('quests');expect(result.panels[1]?.panelType).toBe('quests');expect(result.panels[0]?.filterStatus).not.toBe(result.panels[1]?.filterStatus)});
 it('rejects unknown executable fields at the root and panel level',()=>{expect(()=>validateWorkspaceImport({...portable(),script:'alert(1)'})).toThrow(/not a supported/);const input=portable() as any;input.panels[0].onRender='return window';expect(()=>validateWorkspaceImport(input)).toThrow(/unknown configuration fields/)});
 it('rejects invalid variants, status operators, filters, and bounds',()=>{const wrongVariant=portable() as any;wrongVariant.panels[0].variant='tree';expect(()=>validateWorkspaceImport(wrongVariant)).toThrow(/not allowed/);const wrongFilter=portable() as any;wrongFilter.panels[0].filterStatus="in_progress' OR 1=1";expect(()=>validateWorkspaceImport(wrongFilter)).toThrow(/not allowed/);const wrongLimit=portable() as any;wrongLimit.panels[0].itemLimit=1000;expect(()=>validateWorkspaceImport(wrongLimit)).toThrow(/not allowed/)});
 it('exports only the explicit portable configuration fields, without workspace/player IDs or timestamps',()=>{const workspace:Workspace={id:'w1',playerId:'p1',name:'Python Learning',template:'learning',sortOrder:0,isDefault:true,createdAt:'created',updatedAt:'updated'};const panel={id:'p1',workspaceId:'w1',...base('quests'),variant:'cards',filterStatus:'active',sortBy:'updated_desc',createdAt:'created',updatedAt:'updated'} as unknown as WorkspacePanel;const output=exportWorkspace(workspace,[panel]);expect(output).toEqual({format:'life-rpg-workspace',version:1,workspace:{name:'Python Learning',template:'learning'},panels:[{...base('quests'),variant:'cards',filterStatus:'active',sortBy:'updated_desc'}]});expect(JSON.stringify(output)).not.toContain('playerId');expect(JSON.stringify(output)).not.toContain('createdAt')});
});
