import {
  createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode,
} from 'react';
import type { CoreClient } from '../../domain/ipc';
import type { Concept, Effect, Player, Quest, WorldOverview } from '../../domain/world';
import './EntitySurface.css';

export type SurfaceKind = 'player' | 'quest' | 'concept' | 'effect';
export type SurfaceMode = 'view' | 'edit';
export type EntitySurfaceRecord = { kind: SurfaceKind; id: string; mode: SurfaceMode; returnFocus?: HTMLElement | null };
type SurfaceContextValue = { openSurface:(kind:SurfaceKind,id:string,options?:{mode?:SurfaceMode})=>void; closeSurface:()=>void; backSurface:()=>void; stack:EntitySurfaceRecord[] };
const SurfaceContext=createContext<SurfaceContextValue|null>(null);
export function useEntitySurface(){const context=useContext(SurfaceContext);if(!context)throw new Error('useEntitySurface must be used inside EntitySurfaceProvider');return context;}
export function useOptionalEntitySurface():SurfaceContextValue{return useContext(SurfaceContext)??{openSurface:()=>{},closeSurface:()=>{},backSurface:()=>{},stack:[]};}

type ProviderProps={children:ReactNode;client:CoreClient;player:Player|null;overview:WorldOverview|null;concepts:Concept[];onRefresh:()=>Promise<void>};
type Loaded={record:Player|Quest|Concept|Effect|null; relatedConcepts:Concept[]; loading:boolean};

export function EntitySurfaceProvider({children,client,player,overview,concepts,onRefresh}:ProviderProps){
 const [stack,setStack]=useState<EntitySurfaceRecord[]>([]);const lastTrigger=useRef<HTMLElement|null>(null);
 const openSurface=useCallback((kind:SurfaceKind,id:string,options:{mode?:SurfaceMode}={})=>{if(!id)return;lastTrigger.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setStack(current=>[...current,{kind,id,mode:options.mode??'view',returnFocus:lastTrigger.current}]);},[]);
 const closeSurface=useCallback(()=>{setStack(current=>{const closing=current[current.length-1];window.setTimeout(()=>closing?.returnFocus?.focus(),0);return current.slice(0,-1);});},[]);
 const value=useMemo(()=>({openSurface,closeSurface,backSurface:closeSurface,stack}),[openSurface,closeSurface,stack]);
 return <SurfaceContext.Provider value={value}>{children}{stack.length>0&&<EntitySurfaceStack client={client} player={player} overview={overview} concepts={concepts} onRefresh={onRefresh}/>}</SurfaceContext.Provider>;
}

async function resolveSurface(surface:EntitySurfaceRecord,client:CoreClient,player:Player|null,overview:WorldOverview|null,concepts:Concept[]):Promise<Loaded>{
 if(surface.kind==='player')return {record:player?.id===surface.id?player:null,relatedConcepts:[],loading:false};
 const getOverview=typeof client.getWorldOverview==='function'?client.getWorldOverview.bind(client):async()=>overview;
 const listConcepts=typeof client.listConcepts==='function'?client.listConcepts.bind(client):async()=>concepts;
 const getConcept=typeof client.getConcept==='function'?client.getConcept.bind(client):async(id:string)=>concepts.find(x=>x.id===id)??null;
 const listAssociations=typeof client.listConceptAssociations==='function'?client.listConceptAssociations.bind(client):async()=>[];
 const fresh=player?await getOverview(player.id).catch(()=>overview):overview;
 const freshConcepts=player?await listConcepts(player.id).catch(()=>concepts):concepts;
 let record:Loaded['record']=surface.kind==='quest'?fresh?.quests.find(x=>x.id===surface.id)??null:surface.kind==='concept'?await getConcept(surface.id).catch(()=>freshConcepts.find(x=>x.id===surface.id)??null):fresh?.effects.find(x=>x.id===surface.id)??null;
 if(surface.kind!=='quest'||!record)return {record,relatedConcepts:[],loading:false};
 const related=await Promise.all(freshConcepts.map(async concept=>({concept,links:await listAssociations(concept.id).catch(()=>[])})));
 return {record,relatedConcepts:related.filter(x=>x.links.some(link=>link.entityKind==='quest'&&link.entityId===surface.id&&link.isActive)).map(x=>x.concept),loading:false};
}
function titleOf(kind:SurfaceKind,record:Loaded['record']){if(!record)return 'Unknown record';return kind==='player'?(record as Player).name:kind==='quest'?(record as Quest).title:(record as Concept|Effect).name;}
function titleFor(kind:SurfaceKind,id:string,player:Player|null,overview:WorldOverview|null,concepts:Concept[]){if(kind==='player')return player?.id===id?player.name:'Unknown record';if(kind==='quest')return overview?.quests.find(x=>x.id===id)?.title??'Unknown record';if(kind==='concept')return concepts.find(x=>x.id===id)?.name??'Unknown record';return overview?.effects.find(x=>x.id===id)?.name??'Unknown record';}
function humanCopy(kind:SurfaceKind,record:Loaded['record']){if(!record)return '';if(kind==='player'){const x=record as Player;return `Player: ${x.name}\nLevel: ${x.level}${x.levelName?` · ${x.levelName}`:''}\nExperience: ${x.currentXp.toLocaleString()}\n${x.description??''}`;}if(kind==='quest'){const x=record as Quest;return `Quest: ${x.title}\nStatus: ${x.status.replaceAll('_',' ')}\nProgress: ${x.progress}%\n${x.description??''}`;}if(kind==='concept'){const x=record as Concept;return `Concept: ${x.name}\nType: ${x.typeCode.replaceAll('_',' ')}\nStatus: ${x.isActive?'Active':'Inactive'}\n${x.description??''}`;}const x=record as Effect;return `Effect: ${x.name}\nType: ${x.typeCode.replaceAll('_',' ')}\nStatus: ${x.deactivatedAt?'Inactive':'Active'}\nIntensity: ${x.intensity}\n${x.description??''}`;}

function EntitySurfaceStack({client,player,overview,concepts,onRefresh}:Omit<ProviderProps,'children'>){
 const {stack,closeSurface,backSurface,openSurface}=useEntitySurface();const surface=stack[stack.length-1]!;const [loaded,setLoaded]=useState<Loaded>({record:null,relatedConcepts:[],loading:true});const [editing,setEditing]=useState(surface.mode==='edit');const [copyState,setCopyState]=useState('Copy');const headingRef=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let live=true;setLoaded(x=>({...x,loading:true}));void resolveSurface(surface,client,player,overview,concepts).then(x=>{if(live)setLoaded(x)});return()=>{live=false}},[surface.kind,surface.id,client,player?.id,overview,concepts]);
 useEffect(()=>{setEditing(surface.mode==='edit');setCopyState('Copy');const previous=document.body.style.overflow;document.body.style.overflow='hidden';headingRef.current?.focus();return()=>{document.body.style.overflow=previous};},[surface.kind,surface.id,surface.mode]);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();closeSurface();}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[closeSurface]);
 const copy=async()=>{try{await navigator.clipboard?.writeText(humanCopy(surface.kind,loaded.record));setCopyState('Copied');window.setTimeout(()=>setCopyState('Copy'),1400)}catch{setCopyState('Copy unavailable')}};
 const parent=stack.length>1?stack[stack.length-2]:null;
 return <div className="entity-surface-layer" data-testid="entity-surface-layer"><button className="entity-surface-backdrop" aria-label="Close entity surface" onClick={closeSurface}/><aside className="entity-surface" role="dialog" aria-modal="true" aria-labelledby="entity-surface-title"><header className="entity-surface__header"><div className="entity-surface__heading">{parent&&<button className="text-link" onClick={backSurface}>← Back to {titleFor(parent.kind,parent.id,player,overview,concepts)}</button>}<span className="eyebrow">{surface.kind} · contextual surface</span><h2 id="entity-surface-title" tabIndex={-1} ref={headingRef}>{loaded.loading?'Loading…':titleOf(surface.kind,loaded.record)}</h2><p>Inspect this record without leaving your current workspace.</p></div><button className="entity-surface__close" aria-label="Close entity surface" onClick={closeSurface}>×</button></header><div className="entity-surface__toolbar"><span className="type-pill">{editing?'Editing':'Details'}</span><div>{(surface.kind==='player'||surface.kind==='concept')&&<button className="button button--small button--cyan" onClick={()=>setEditing(x=>!x)}>{editing?'Cancel edit':'Edit'}</button>}{!editing&&<button className="button button--small" onClick={()=>void copy()}>{copyState}</button>}</div></div><div className="entity-surface__body">{loaded.loading?<p className="muted">Resolving the saved record…</p>:!loaded.record?<p className="muted">This record is no longer available in the current world.</p>:surface.kind==='player'?<PlayerSurface player={loaded.record as Player} client={client} editing={editing} setEditing={setEditing} onRefresh={onRefresh}/>:surface.kind==='quest'?<QuestSurface quest={loaded.record as Quest} concepts={loaded.relatedConcepts} openSurface={openSurface}/>:surface.kind==='concept'?<ConceptSurface concept={loaded.record as Concept} concepts={concepts} client={client} editing={editing} setEditing={setEditing} onRefresh={onRefresh} openSurface={openSurface}/>:<EffectSurface effect={loaded.record as Effect}/>}</div></aside></div>;
}
function Field({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="entity-field"><span>{label}</span><strong className={mono?'selectable':undefined}>{value||'—'}</strong></div>}
function EntitySection({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <section className="entity-section"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div>{children}</section>}
function PlayerSurface({player,client,editing,setEditing,onRefresh}:{player:Player;client:CoreClient;editing:boolean;setEditing:(value:boolean)=>void;onRefresh:()=>Promise<void>}){const[level,setLevel]=useState(String(player.level));const[levelName,setLevelName]=useState(player.levelName??'');const[progressionLabel,setProgressionLabel]=useState(player.progressionLabel??'');const[message,setMessage]=useState('');useEffect(()=>{setLevel(String(player.level));setLevelName(player.levelName??'');setProgressionLabel(player.progressionLabel??'')},[player]);async function save(){await client.setPlayerProgression(player.id,Number(level),levelName||undefined,progressionLabel||undefined);await onRefresh();setEditing(false);setMessage('Player details saved.')}return <><EntitySection eyebrow="Identity" title="Player record"><div className="entity-grid"><Field label="Name" value={player.name}/><Field label="Level" value={String(player.level)}/><Field label="Experience" value={player.currentXp.toLocaleString()}/><Field label="Record ID" value={player.id} mono/></div><p className="entity-copy">{player.description||'Your Player record is the authored centre of this world.'}</p></EntitySection>{editing&&<EntitySection eyebrow="Edit mode" title="Player-authored progression"><div className="entity-form"><label>Level<input type="number" min="1" value={level} onChange={e=>setLevel(e.target.value)}/></label><label>Level title<input value={levelName} onChange={e=>setLevelName(e.target.value)}/></label><label>Progression note<textarea rows={3} value={progressionLabel} onChange={e=>setProgressionLabel(e.target.value)}/></label><div><button className="button button--primary" onClick={()=>void save()}>Save</button><button className="button button--quiet" onClick={()=>setEditing(false)}>Cancel</button></div></div></EntitySection>}{message&&<p className="inline-feedback" role="status">{message}</p>}</>}
function QuestSurface({quest,concepts,openSurface}:{quest:Quest;concepts:Concept[];openSurface:SurfaceContextValue['openSurface']}){return <><EntitySection eyebrow="Identity" title="Quest details"><div className="entity-grid"><Field label="Status" value={String(quest.status??'').replaceAll('_',' ')}/><Field label="Progress" value={`${quest.progress}%`}/><Field label="Type" value={String(quest.typeCode??'').replaceAll('_',' ')}/><Field label="Record ID" value={quest.id} mono/></div><p className="entity-copy">{quest.description||'No description has been recorded for this Quest.'}</p></EntitySection><EntitySection eyebrow="Actual relationships" title="Attached Concepts">{concepts.length?concepts.map(concept=><button className="entity-relation" key={concept.id} onClick={()=>openSurface('concept',concept.id)}><span>Concept · {String(concept.typeCode??'').replaceAll('_',' ')}</span><strong>{concept.name}</strong><small>Open this related Concept →</small></button>):<p className="muted">No Concepts are actually attached to this Quest.</p>}</EntitySection></>}
function ConceptSurface({concept,concepts,client,editing,setEditing,onRefresh,openSurface}:{concept:Concept;concepts:Concept[];client:CoreClient;editing:boolean;setEditing:(value:boolean)=>void;onRefresh:()=>Promise<void>;openSurface:SurfaceContextValue['openSurface']}){const[active,setActive]=useState(concept.isActive);const[message,setMessage]=useState('');const[relations,setRelations]=useState<import('../../domain/world').ConceptRelationship[]>([]);useEffect(()=>{setActive(concept.isActive);void client.listConceptRelationships(concept.id).then(setRelations).catch(()=>setRelations([]))},[concept,client]);async function save(){await client.setConceptActive(concept.id,active);await onRefresh();setEditing(false);setMessage('Concept details saved.')}return <><EntitySection eyebrow="Identity" title="Concept details"><div className="entity-grid"><Field label="Type" value={concept.typeCode.replaceAll('_',' ')}/><Field label="Status" value={concept.isActive?'Active':'Inactive'}/><Field label="Record ID" value={concept.id} mono/></div><p className="entity-copy">{concept.description||'This Concept is ready to collect meaning and relationships.'}</p></EntitySection><EntitySection eyebrow="Actual relationships" title="Related Concepts">{relations.length?relations.map(relation=>{const id=relation.sourceConceptId===concept.id?relation.targetConceptId:relation.sourceConceptId;const related=concepts.find(x=>x.id===id);return related?<button className="entity-relation" key={relation.id} onClick={()=>openSurface('concept',related.id)}><span>{relation.relationshipCode.replaceAll('_',' ')}</span><strong>{related.name}</strong><small>Open this related Concept →</small></button>:null}):<p className="muted">No related Concepts are recorded.</p>}</EntitySection>{editing&&<EntitySection eyebrow="Edit mode" title="Concept state"><div className="entity-form"><label className="entity-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active in this world</label><div><button className="button button--primary" onClick={()=>void save()}>Save</button><button className="button button--quiet" onClick={()=>setEditing(false)}>Cancel</button></div></div></EntitySection>}{message&&<p className="inline-feedback" role="status">{message}</p>}</>}
function EffectSurface({effect}:{effect:Effect}){return <EntitySection eyebrow="Current state" title="Effect details"><div className="entity-grid"><Field label="Status" value={effect.deactivatedAt?'Inactive':'Active'}/><Field label="Type" value={effect.typeCode.replaceAll('_',' ')}/><Field label="Intensity" value={String(effect.intensity)}/><Field label="Record ID" value={effect.id} mono/></div><p className="entity-copy">{effect.description||'No description has been recorded for this Effect.'}</p></EntitySection>}
