import { useCallback, useEffect, useState } from 'react';
import { AppShell, type AppRoute } from './app/AppShell';
import { coreClient } from './domain/ipc';
import type { Concept, Player, PlayerStat, QuestSession, SearchHit, WorldOverview, Workspace, WorkspacePanel, WorkspaceTemplate } from './domain/world';
import { WORKSPACE_TEMPLATES } from './features/workspaces/templates';
import { PANEL_REGISTRY } from './features/workspaces/panelRegistry';
import type { PortableWorkspace } from './features/workspaces/workspaceTransfer';
import { RulePanel } from './features/world/RulePanel';
import { StatusScreen } from './features/status/StatusScreen';
import { WorldWorkspace } from './features/world/WorldWorkspace';

const ACTIVE_WORLD_KEY='life-rpg.active-world.v1'; const ACTIVE_ROUTE_KEY='life-rpg.active-route.v1';
const localGet=(key:string):string|null=>{try{return localStorage.getItem(key)}catch{return null}};const localSet=(key:string,value:string)=>{try{localStorage.setItem(key,value)}catch{}};const localRemove=(key:string)=>{try{localStorage.removeItem(key)}catch{}};
const activeWorkspaceKey=(playerId:string)=>`life-rpg.active-workspace.v1.${playerId}`;
const knownRoutes:AppRoute[]=['dashboard','player','quests','skills','skillTrees','concepts','effects','journal','explorer','history','rules','status'];
const emptyQuery={text:null,kind:'player',playerId:null,conceptId:null,typeCode:null,status:null,active:null,from:null,through:null,context:null,includeHidden:true,includeArchived:true,includeTrashed:true,sort:'name' as const,limit:250,offset:0};

export function App(){
 const [route,setRoute]=useState<AppRoute>(()=>{const saved=localGet(ACTIVE_ROUTE_KEY) as AppRoute|null;return saved&&knownRoutes.includes(saved)?saved:'dashboard'});
 const [players,setPlayers]=useState<{id:string;name:string}[]>([]); const [player,setPlayer]=useState<Player|null>(null);
 const [workspaces,setWorkspaces]=useState<Workspace[]>([]); const [workspace,setWorkspace]=useState<Workspace|null>(null); const [workspacePanels,setWorkspacePanels]=useState<WorkspacePanel[]>([]);
 const [overview,setOverview]=useState<WorldOverview|null>(null); const [concepts,setConcepts]=useState<Concept[]>([]); const [stats,setStats]=useState<PlayerStat[]>([]); const [sessions,setSessions]=useState<QuestSession[]>([]);
 const [healthReady,setHealthReady]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [quickCreate,setQuickCreate]=useState(false);
 const refreshWorld=useCallback(async(id=player?.id)=>{if(!id)return;try{const [world,conceptRows,statRows,sessionRows]=await Promise.all([coreClient.getWorldOverview(id),coreClient.listConcepts(id),coreClient.listPlayerStats(id),coreClient.listQuestSessions(id)]);setPlayer(world.player);setOverview(world);setConcepts(conceptRows);setStats(statRows);setSessions(sessionRows);setError('')}catch(e){setError(e instanceof Error?e.message:'The local world could not be loaded.')}},[player?.id]);
 const seedWorkspace=useCallback(async(playerId:string,name:string,template:WorkspaceTemplate,isDefault=false)=>{const def=WORKSPACE_TEMPLATES.find(x=>x.id===template);const created=await coreClient.createWorkspace(playerId,name,template,isDefault);const panels:WorkspacePanel[]=[];for(const [sortOrder,p] of (def?.panels??[]).entries()){panels.push(await coreClient.saveWorkspacePanel({playerId,workspaceId:created.id,panelType:p.panelType,title:p.title,variant:p.variant,density:p.density,filterStatus:p.filterStatus??null,filterActive:p.filterActive??null,filterTypeCode:p.filterTypeCode??null,filterConceptId:null,filterRecentDays:p.filterRecentDays??null,sortBy:p.sortBy,itemLimit:p.itemLimit,sortOrder,gridSpan:p.gridSpan??1,isVisible:true,isPinned:p.isPinned,isCollapsed:false}))}return{created,panels}},[]);
 const loadWorkspace=useCallback(async(playerId:string)=>{let rows=await coreClient.listWorkspaces(playerId);if(rows.length===0){let legacy:unknown[]=[];try{const raw=localGet('life-rpg.dashboard-panels.v1');const value=raw?JSON.parse(raw):[];if(Array.isArray(value))legacy=value}catch{}const allowed=['quests','skills','concepts','effects','activity','transactions','journal'] as const;const usable=legacy.filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object'&&allowed.includes((x as Record<string,unknown>).id as typeof allowed[number])&&((x as Record<string,unknown>).visible!==false)).slice(0,50);if(usable.length){const created=await coreClient.createWorkspace(playerId,'My Dashboard','custom',true);for(const [order,row] of usable.entries()){const panelType=row.id as typeof allowed[number];const definition=PANEL_REGISTRY[panelType];const variant=definition.variants.includes(row.variant as WorkspacePanel['variant'])?row.variant as WorkspacePanel['variant']:definition.defaultVariant;const density=row.density==='compact'?'compact':'cozy';const title=typeof row.title==='string'?row.title.trim().slice(0,120)||undefined:undefined;const limit=typeof row.limit==='number'&&Number.isFinite(row.limit)?Math.max(1,Math.min(50,Math.trunc(row.limit))):6;await coreClient.saveWorkspacePanel({playerId,workspaceId:created.id,panelType,title:title??null,variant,density,filterStatus:null,filterActive:null,filterTypeCode:null,filterConceptId:null,filterRecentDays:null,sortBy:definition.defaultSort,itemLimit:limit,sortOrder:order,gridSpan:1,isVisible:true,isPinned:row.pinned===true,isCollapsed:row.collapsed===true})}localRemove('life-rpg.dashboard-panels.v1')}else await seedWorkspace(playerId,'Overview','overview',true);rows=await coreClient.listWorkspaces(playerId)}const preferred=localGet(activeWorkspaceKey(playerId));const selected=rows.find(w=>w.id===preferred)??rows.find(w=>w.isDefault)??rows[0]??null;setWorkspaces(rows);setWorkspace(selected);if(selected){localSet(activeWorkspaceKey(playerId),selected.id);setWorkspacePanels(await coreClient.listWorkspacePanels(playerId,selected.id))}else setWorkspacePanels([])},[seedWorkspace]);
 const createWorkspace=useCallback(async(name:string,template:WorkspaceTemplate)=>{if(!player)return;const result=await seedWorkspace(player.id,name,template,false);const rows=await coreClient.listWorkspaces(player.id);setWorkspaces(rows);setWorkspace(result.created);setWorkspacePanels(result.panels);localSet(activeWorkspaceKey(player.id),result.created.id);setNotice(`${name} workspace created.`);setError('')},[player,seedWorkspace]);
 const chooseWorkspace=useCallback(async(id:string)=>{const next=workspaces.find(w=>w.id===id);if(!next||!player)return;try{const panels=await coreClient.listWorkspacePanels(player.id,id);setWorkspace(next);localSet(activeWorkspaceKey(player.id),id);setWorkspacePanels(panels);setError('')}catch(e){setError(e instanceof Error?e.message:'Workspace could not be opened.')}},[player,workspaces]);
 const renameWorkspace=useCallback(async(name:string)=>{if(!player||!workspace)return;await coreClient.renameWorkspace(player.id,workspace.id,name);const rows=await coreClient.listWorkspaces(player.id);setWorkspaces(rows);setWorkspace(rows.find(w=>w.id===workspace.id)??workspace);setNotice('Workspace renamed.')},[player,workspace]);
 const makeDefault=useCallback(async()=>{if(!player||!workspace)return;await coreClient.setDefaultWorkspace(player.id,workspace.id);const rows=await coreClient.listWorkspaces(player.id);setWorkspaces(rows);setWorkspace(rows.find(w=>w.id===workspace.id)??workspace);setNotice('Default workspace updated. Active view stays open.')},[player,workspace]);
 const deleteWorkspace=useCallback(async()=>{if(!player||!workspace)return;await coreClient.deleteWorkspace(player.id,workspace.id);const rows=await coreClient.listWorkspaces(player.id);if(rows.length===0)throw new Error('A world must retain one workspace.');const next=rows.find(w=>w.isDefault)??rows[0]!;const panels=await coreClient.listWorkspacePanels(player.id,next.id);setWorkspaces(rows);setWorkspace(next);setWorkspacePanels(panels);localSet(activeWorkspaceKey(player.id),next.id);setNotice('Workspace removed; underlying world records were not changed.')},[player,workspace]);
 const copyPanels=async(source:WorkspacePanel[],playerId:string,target:Workspace)=>{const result:WorkspacePanel[]=[];for(const p of source)result.push(await coreClient.saveWorkspacePanel({playerId,workspaceId:target.id,panelType:p.panelType,title:p.title,variant:p.variant,density:p.density,filterStatus:p.filterStatus,filterActive:p.filterActive,filterTypeCode:p.filterTypeCode,filterConceptId:p.filterConceptId,filterRecentDays:p.filterRecentDays,sortBy:p.sortBy,itemLimit:p.itemLimit,sortOrder:p.sortOrder,gridSpan:p.gridSpan,isVisible:p.isVisible,isPinned:p.isPinned,isCollapsed:p.isCollapsed}));return result};
 const duplicateWorkspace=useCallback(async(name:string)=>{if(!player||!workspace)return;const created=await coreClient.createWorkspace(player.id,name,'custom',false);const panels=await copyPanels(workspacePanels,player.id,created);const rows=await coreClient.listWorkspaces(player.id);setWorkspaces(rows);setWorkspace(created);setWorkspacePanels(panels);localSet(activeWorkspaceKey(player.id),created.id);setNotice('Workspace duplicated with independent panel configuration.')},[player,workspace,workspacePanels]);
 const importWorkspace=useCallback(async(value:PortableWorkspace)=>{if(!player)return;const created=await coreClient.createWorkspace(player.id,value.workspace.name,value.workspace.template,false);const panels:WorkspacePanel[]=[];for(const p of value.panels)panels.push(await coreClient.saveWorkspacePanel({playerId:player.id,workspaceId:created.id,...p}));const rows=await coreClient.listWorkspaces(player.id);setWorkspaces(rows);setWorkspace(created);setWorkspacePanels(panels);localSet(activeWorkspaceKey(player.id),created.id)},[player]);
 useEffect(()=>{let live=true;async function boot(){setLoading(true);try{const [hits]=await Promise.all([coreClient.searchWorld(emptyQuery),coreClient.ping()]);if(!live)return;const choices=hits.filter((h:SearchHit)=>h.kind==='player').map(h=>({id:h.id,name:h.name}));setPlayers(choices);setHealthReady(true);const saved=localGet(ACTIVE_WORLD_KEY);const selected=choices.find(p=>p.id===saved)??choices[0];if(selected){const loaded=await coreClient.getPlayer(selected.id);if(live&&loaded){localSet(ACTIVE_WORLD_KEY,selected.id);setPlayer(loaded);const [world,conceptRows,statRows,sessionRows]=await Promise.all([coreClient.getWorldOverview(selected.id),coreClient.listConcepts(selected.id),coreClient.listPlayerStats(selected.id),coreClient.listQuestSessions(selected.id)]);if(live){setPlayer(world.player);setOverview(world);setConcepts(conceptRows);setStats(statRows);setSessions(sessionRows);await loadWorkspace(selected.id)}}}}catch(e){if(live){setHealthReady(false);setError(e instanceof Error?e.message:'The local world could not be reached.')}}finally{if(live)setLoading(false)}}void boot();return()=>{live=false}},[loadWorkspace]);
 const selectPlayer=useCallback(async(id:string)=>{if(!id)return;localSet(ACTIVE_WORLD_KEY,id);setLoading(true);setError('');try{const [world,conceptRows,statRows,sessionRows]=await Promise.all([coreClient.getWorldOverview(id),coreClient.listConcepts(id),coreClient.listPlayerStats(id),coreClient.listQuestSessions(id)]);setPlayer(world.player);setOverview(world);setConcepts(conceptRows);setStats(statRows);setSessions(sessionRows);await loadWorkspace(id)}catch(e){setError(e instanceof Error?e.message:'Could not switch world.')}finally{setLoading(false)}},[loadWorkspace]);
 const createPlayer=useCallback(async(name:string,description?:string)=>{const created=await coreClient.createPlayer(name,description);localSet(ACTIVE_WORLD_KEY,created.id);setPlayers(rows=>[...rows,{id:created.id,name:created.name}]);setPlayer(created);await refreshWorld(created.id);await loadWorkspace(created.id);setNotice(`World created for ${created.name}.`)},[refreshWorld,loadWorkspace]);
 const afterMutation=useCallback(async(message?:string)=>{await refreshWorld();if(message)setNotice(message)},[refreshWorld]);const quickNavigate=(next:AppRoute)=>{setQuickCreate(false);setRoute(next)};useEffect(()=>{localSet(ACTIVE_ROUTE_KEY,route)},[route]);
 return <AppShell route={route} onNavigate={setRoute} player={player} players={players} onPlayerChange={id=>void selectPlayer(id)} workspaces={workspaces} workspace={workspace} onWorkspaceChange={id=>void chooseWorkspace(id)} onCreate={()=>setQuickCreate(true)} ready={healthReady}>
  {notice&&<div className="notice-bar" role="status"><span>{notice}</span><button className="text-link" onClick={()=>setNotice('')} aria-label="Dismiss notification">Dismiss</button></div>}{error&&<div className="error-banner" role="alert"><strong>World unavailable</strong><span>{error}</span><button className="button button--small" onClick={()=>void refreshWorld()}>Retry</button></div>}{loading&&<div className="loading-state" role="status"><span className="loading-dot"/>Loading your world…</div>}
  {!loading&&(!player||!overview)?<WorldWorkspace route={route} client={coreClient} player={null} overview={null} concepts={[]} stats={[]} sessions={[]} workspace={null} workspaces={[]} panels={[]} onPanelsChange={setWorkspacePanels} onCreateWorkspace={createWorkspace} onRenameWorkspace={renameWorkspace} onDefaultWorkspace={makeDefault} onDeleteWorkspace={deleteWorkspace} onDuplicateWorkspace={duplicateWorkspace} onImportWorkspace={importWorkspace} onRefresh={afterMutation} onCreatePlayer={createPlayer} onNavigate={setRoute}/>:!loading&&player&&overview&&<WorldWorkspace route={route} client={coreClient} player={player} overview={overview} concepts={concepts} stats={stats} sessions={sessions} workspace={workspace} workspaces={workspaces} panels={workspacePanels} onPanelsChange={setWorkspacePanels} onCreateWorkspace={createWorkspace} onRenameWorkspace={renameWorkspace} onDefaultWorkspace={makeDefault} onDeleteWorkspace={deleteWorkspace} onDuplicateWorkspace={duplicateWorkspace} onImportWorkspace={importWorkspace} onRefresh={afterMutation} onCreatePlayer={createPlayer} onNavigate={setRoute}/>}
  {route==='rules'&&player&&<RulePanel playerId={player.id} client={coreClient}/ >}{route==='status'&&<StatusScreen/>}
  {quickCreate&&<div className="modal-backdrop" role="presentation" onClick={()=>setQuickCreate(false)}><section className="quick-create" role="dialog" aria-modal="true" aria-labelledby="quick-create-title" onClick={e=>e.stopPropagation()}><button className="quick-create__close" aria-label="Close" onClick={()=>setQuickCreate(false)}>×</button><p className="eyebrow">Start with a record</p><h2 id="quick-create-title">Create in this world</h2><p className="muted">Choose what you want to add. Your entry stays local and editable.</p><div className="quick-create__grid">{([{label:'Quest',route:'quests'},{label:'Skill tree',route:'skills'},{label:'Concept',route:'concepts'},{label:'Journal entry',route:'journal'}] as const).map(x=><button className="quick-create__choice" key={x.route} onClick={()=>quickNavigate(x.route)}><span>＋</span>{x.label}<small>Open creation form</small></button>)}</div></section></div>}
 </AppShell>;
}
